name: Deploy React App to MicroK8s

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_UN }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build Docker image  # Build Docker image
        run: |
            $tag = "puck-ui:$(& git rev-parse --short HEAD)-$(Get-Date -Format 'yyyyMMddHHmmss')"
            Write-Output $tag
            docker build -t "smehi/$tag" .
            docker push "smehi/$tag"
  
            $content = Get-Content -Path "C:\Windows\System32\actions-runner\_work\puck-ui\puck\puck-deploy.yaml" -Raw
            $newContent = $content -replace "puck-ui:latest", $tag
            $newContent | Set-Content -Path "C:\Windows\System32\actions-runner\_work\puck-ui\puck\puck-deploy.yaml"

  deploy:
    name: kubernetes deploy
    environment:
      name: dev
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
  
    - name: Delete old deployment
      continue-on-error: true
      run: kubectl delete deployment puck-ui-app --kubeconfig=$HOME\.kube\config\client.config

    - name: Wait For Deployment To Start
      run: Start-Sleep -Seconds 12
      
    - name: Apply pods
      run: kubectl apply -f deployment.yaml --kubeconfig=$HOME\.kube\config\client.config
    
    - name: Wait For Deployment To Start
      run: Start-Sleep -Seconds 10
      
    - name: Wait For Pods To Start
      run: kubectl wait --for=condition=ready pod -l app=puck-ui --timeout=1m --kubeconfig=$HOME\.kube\config\client.config
      
